language: php

php:
    - '7.1'

addons:
    hosts:
        - php
        - httpd
        - mongo

services:
    - mongodb

branches:
    only:
        - master

install:
    - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    # Enabling mongodb php extension & disabling xdebug
    - echo 'extension = mongodb.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - phpenv config-rm xdebug.ini
    # Debuging
    - mongo .travis/enable-mongo-logs.js

before_script:
    # Selenium
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - wget https://goo.gl/hvDPsK -O selenium-server-standalone.jar
    - java -jar selenium-server-standalone.jar > /dev/null &
    - sleep 5
    # Place into the right directory
    - cd htdocs/
    # Create user on MongoDB
    - sleep 15
    - mongo admin --eval 'db.createUser({user:"admin",pwd:"admin",roles:["root"]});'
    - cp app/config/config_dev.yml.dist app/config/config_dev.yml
    # Installing dependencies
    - composer install --prefer-source --optimize-autoloader
    - php -S localhost:8080 -t web/ &

script:
    - vendor/bin/behat --no-snippets --verbose
#    - bin/phpunit.phar
#    - vendor/bin/phpspec run -fpretty

after_failure:
    - cat var/logs/test.log
    - mongo ../.travis/debug-mongo.js




