imports:
    - { resource: config_dev.yml }

parameters:
    locale: en

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory_users:
            memory:
                users:
                    ROLE_USERS:
                        password: "ROLE_USERS"
                        roles: ['ROLE_USERS']
                    ROLE_RESTAURANT_CV:
                        password: "ROLE_RESTAURANT_CV"
                        roles: ['ROLE_RESTAURANT_CV']
                    ROLE_RESTAURANT_MH:
                        password: "ROLE_RESTAURANT_MH"
                        roles: ['ROLE_RESTAURANT_MH']
                    ROLE_RESTAURANT_DR:
                        password: "ROLE_RESTAURANT_DR"
                        roles: ['ROLE_RESTAURANT_DR']
                    ROLE_SUPERVISOR:
                        password: "ROLE_SUPERVISOR"
                        roles: ['ROLE_SUPERVISOR']
                    ROLE_FRANCHISE:
                        password: "ROLE_FRANCHISE"
                        roles: ['ROLE_FRANCHISE']
                    ROLE_ADMIN:
                        password: "ROLE_ADMIN"
                        roles: ['ROLE_ADMIN']

doctrine_mongodb:
    connections:
        default:
            server: "mongodb://localhost:27017"
            options:
                db: "%mongodb.database%"
                username: "%mongodb.username%"
                password: "%mongodb.password%"