imports:
    - { resource: config_dev.yml }

parameters:
    locale: en

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory_users:
            memory:
                users:
                    ROLE_USERS:
                        password: "ROLE_USERS"
                        roles: ['ROLE_USERS']
                    ROLE_SUPERVISOR:
                        password: "ROLE_SUPERVISOR"
                        roles: ['ROLE_SUPERVISOR']
                    ROLE_FRANCHISE:
                        password: "ROLE_FRANCHISE"
                        roles: ['ROLE_FRANCHISE']
                    ROLE_ADMIN:
                        password: "ROLE_ADMIN"
                        roles: ['ROLE_ADMIN']
