# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    fabrice:
                        password: fabrice
                        roles: ['ROLE_ADMIN']

    # ROLES :
    # ROLE_USERS
    # ROLE_RESTAURANT_CV
    # ROLE_RESTAURANT_MH
    # ROLE_RESTAURANT_DR
    # ROLE_SUPERVISOR
    # ROLE_FRANCHISE
    # ROLE_ADMIN
    role_hierarchy:
        ROLE_RESTAURANT_CV: [ROLE_USERS]
        ROLE_RESTAURANT_MH: [ROLE_USERS]
        ROLE_RESTAURANT_DR: [ROLE_USERS]
        ROLE_SUPERVISOR: [ROLE_RESTAURANT_CV, ROLE_RESTAURANT_MH, ROLE_RESTAURANT_DR]
        ROLE_FRANCHISE: [ROLE_SUPERVISOR]
        ROLE_ADMIN: [ROLE_ALLOWED_TO_SWITCH, ROLE_FRANCHISE, ROLE_SUPERVISOR]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                provider: in_memory
                check_path:           security_login_check
                username_parameter:   login
                password_parameter:   password
                login_path:           security_login

            logout:
                path: security_logout

            switch_user:
                parameter: _admin_switch_user




    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USERS }