# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        AppBundle\Document\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory_users:
            memory:
                users:
                    admin:
                        password: "$2a$10$d.rfCQmi6YulyoUWhvSmxOz60tCoxP8eWk0KTiCIjFPDl.kZkgngi"
                        roles: ['ROLE_ADMIN']

        mongodb_users_username:
            mongodb:
                class: AppBundle:User
                property: username

        mongodb_users_email:
            mongodb:
                class: AppBundle:User
                property: email

        app_users:
            chain:
                providers: [in_memory_users, mongodb_users_username, mongodb_users_email]

    # ROLES :
    # ROLE_USERS
    # ROLE_RESTAURANT_CV
    # ROLE_RESTAURANT_MH
    # ROLE_RESTAURANT_DR
    # ROLE_SUPERVISOR
    # ROLE_FRANCHISE
    # ROLE_ADMIN
    role_hierarchy:
        ROLE_SUPERVISOR: [ROLE_USERS]
        ROLE_FRANCHISE: [ROLE_SUPERVISOR]
        ROLE_ADMIN: [ROLE_ALLOWED_TO_SWITCH, ROLE_FRANCHISE, ROLE_SUPERVISOR]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|bower_components|dist|plugins)/
            security: false

        main:
            provider: app_users
            security: true
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: security_login
                check_path: security_login_check
                username_parameter: login
                password_parameter: password
                success_handler: AppBundle\Security\LoginSuccessHandler
                failure_handler: AppBundle\Security\LoginFailureHandler

            logout:
                path: security_logout
                invalidate_session: false
                success_handler: AppBundle\Security\LogoutSuccessHandler

            switch_user:
                provider: in_memory_users
                parameter: _admin_switch_user
                role: ROLE_ALLOWED_TO_SWITCH

            logout_on_user_change: true

            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                always_remember_me: true



    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USERS }